version: "1"
rules:                      # Array of rules
  - base: dev            # Target (fork) branch
    upstream: Team-Denver:dev    # Upstream branch.
    mergeMethod: hardreset  # Consider using "merge" instead of "hardreset".
  - base: feature           # Change "feature" to the name of the feature your fork represents.
    upstream: dev        # Trickle changes down from dev to your feature branch. Sub-team leads will resolve merge conflicts.
    assignees:              # Sub-team leads
      - stacalpha
    reviewers:              # Sub-team leads
      - stacalpha
      
      # Add additional rules if you need to configure auto-pull to each sub-team members working branch.
label: ":arrow_heading_down: pull"  # Optional
